### ISSUE TITLE
Do you mean lib, not app?

### ISSUE THREAD

**Issue by darkcohiba** [learn-co-curriculum/python-p3-working-with-seed-data#10]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204326?module_item_id=468321

### Concern

These are the instructions but I dont see an app to cd into,

This lesson is set up as a code-along, so make sure to fork and clone the lesson. Then run these commands to set up the dependencies and set up the database:

 pipenv install && pipenv shell

 => Installing dependencies from Pipfile.lock (xxxxxx)...
 =>   🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ X/X — XX:XX:XX
 => To activate this projects virtualenv, run pipenv shell.
 => Alternatively, run a command inside the virtualenv with pipenv run.
 => Launching subshell in virtual environment...
 =>  . /python-p3-working-with-seed-data/.venv/bin/activate
 => $  . /python-p3-working-with-seed-data/.venv/bin/activate

 cd app && alembic upgrade head

**Comment by professor-ben** [comment]
This should be `lib`! We're trying to stay consistent on that front throughout Phase 3. Phase 4 uses `server`.

**Comment by professor-ben** [comment]
All set! The change should be visible on GitHub now and in the Canvas course this evening.

-Ben
