### ISSUE TITLE
Order of operations and missing instructions?

### ISSUE THREAD

**Issue by sheenasany** [learn-co-curriculum/python-p3-working-with-seed-data#11]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204326?module_item_id=468321

### Concern

So I feel that there may be some things that are out of order or missing if this is a code along for students. 

- When adding the new Candy Crush Saga game in the seed.py file, there is no mention to add ccs to the session.bulk_save_objects line. So it will not be saved when running seed.py again and when students go to query the last saved game, it will not appear. Perhaps reminding students to add ccs variable in the bulk save method might clear up any confusion. 

- The way the example shows the add session.query(Game).delete() before the session.commit() could be confusing. 

![image](https://user-images.githubusercontent.com/105241920/222836765-10d4ad3b-d840-4f05-8bcc-c311d0769b27.png)

Perhaps if we include a more conclusive example, this might clear up some confusion as well. 

![image](https://user-images.githubusercontent.com/105241920/222836996-56f84b96-5aba-4a83-95c6-261c5af2f7ef.png)

- Links for the Faker Library and built in randomized data generator send to you to a 404 page. Perhaps we need to replace those with this: [Faker Library](https://faker.readthedocs.io/en/master/) and this: [built-in randomized data generators](https://faker.readthedocs.io/en/master/providers.html)

**Comment by professor-ben** [comment]
I made a few changes here that should help out- the links seem to have been broken due to a stray bracket at the end of the Faker URL, so those should be fixed as well.
