### ISSUE TITLE
GitHub link returns a 404 error

### ISSUE THREAD

**Issue by bricknet1** [learn-co-curriculum/python-p3-working-with-seed-data#12]
### Canvas Link

https://learning.flatironschool.com/courses/6258/assignments/231400?module_item_id=541580

### Concern

The OctoCat icon (as well as the flag icon to report an issue) is a broken link. When viewing this Canvas lesson:
https://learning.flatironschool.com/courses/6258/assignments/231400?module_item_id=541580
The GitHub link associated with the Octocat logo sends you here:
https://github.com/learn-co-curriculum/python-p3-working-with-seed-data-pt2
That repo does not appear to exist. I'm reporting this on a similarly-named but different repo because I'm not sure where else to report it.

**Comment by professor-ben** [comment]
Thanks for raising this issue. There's something goofy going on with the permissions for this repo. We'll try to push a fix later today.

**Comment by professor-ben** [comment]
This arose from the repository being marked "Internal". It has been changed to "Public" and should be accessible through the Octocat button in Canvas.

Thanks,
Ben
