### ISSUE TITLE
Typo: list comprehension, not list interpretation!

### ISSUE THREAD

**Issue by mikecoux** [learn-co-curriculum/python-p3-working-with-seed-data#13]
### Canvas Link

https://learning.flatironschool.com/courses/6329/assignments/239718?module_item_id=563722

### Concern

theres a typo towards the bottom of the lab. see title ^

**Comment by Gehrig-Barnes** [comment]
I didn't see any typos in the lab. Maybe the student is talking about the material written on canvas?

**Comment by professor-ben** [comment]
I found this in one of the dropdowns- this is fixed now. Thanks for reporting.

-Ben
