### ISSUE TITLE
Incorrect path referenced in `Using the seed.py File`

### ISSUE THREAD

**Issue by viewsdevelop** [learn-co-curriculum/python-p3-working-with-seed-data#3]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204326?module_item_id=468321

### Concern

<img width="427" alt="Screen Shot 2022-09-13 at 12 05 37 PM" src="https://user-images.githubusercontent.com/24566696/189963959-31a824b3-8c91-4959-a51c-7ec2ab2f5ac8.png">

The image points to `db/seed.py`, but it's actually located at `app/seed.py`. The correct location is noted in the text above the image. However, below the image, the instructions also appear to be incorrect `To run this code, simply run python db/seed.py.`

### Suggested Changes

Replace `db/seed.py` with `app/seed.py`.

**Comment by professor-ben** [comment]
thanks, this was a refactor. i'll update now.
